

static char NavBarStyleSheet[] =
/* Reset */
  "*{\n"
    "margin: 0;\n"
    "padding: 0;\n"
    "box-sizing: border-box;\n"
  "}\n"
  "body{\n"
    "background-color: var(--white);\n"
    "font-family: \"Poppins\", sans-serif;\n"
  "}\n"
  "a{\n"
    "text-decoration: none;\n"
  "}\n"
  "ul{\n"
    "list-style: none;\n"
  "}\n"
  /* Header */
  ".header {\n"
    "background-color: var(--black);\n"
    "box-shadow: 1px 1px 5px 0px var(--gray);\n"
    "position: sticky;\n"
    "top: 0;\n"
    "width: 100%;\n"
  "}\n"
  /* Title */
  ".logo{\n"
    "display: inline-block;\n"
    "color: var(--white);\n"
    "font-size: 60px;\n"
    "margin-left: 10px;\n"
  "}"
  /* Nav menu */
  ".nav{"
    "width: 100%;\n"
    "height: 100%;\n"
    "position: fixed;\n"
    "top: 80px;\n"
    "background-color: var(--black);\n"
    "overflow: hidden;\n"
  "}\n"
  ".menu a{\n"
    "display: block;\n"
    "padding: 30px;\n"
    "color: var(--white);\n"
  "}\n"
  ".menu a:hover{\n"
    "background-color: var(--gray);\n"
  "}\n"
  ".nav{\n"
    "max-height: 0;\n"
    "transition: max-height .5s ease-out;\n"
  "}\n"
  ".hamb{\n"
    "cursor: pointer;\n"
    "float: right;\n"
    "padding: 40px 20px;\n"
  "}\n"
  /* Style label tag */

  ".hamb-line {\n"
    "background: var(--white);\n"
    "display: block;\n"
    "height: 2px;\n"
    "position: relative;\n"
    "width: 24px;\n"
  "}\n" 
  /* Style span tag */

  ".hamb-line::before,\n"
  ".hamb-line::after{\n"
    "background: var(--white);\n"
    "content: '';\n"
    "display: block;\n"
    "height: 100%;\n"
    "position: absolute;\n"
    "transition: all .2s ease-out;\n"
    "width: 100%;\n"
  "}\n"
  ".hamb-line::before{\n"
    "top: 5px;\n"
  "}\n"
  ".hamb-line::after{\n"
    "top: -5px;"
  "}\n"

  ".side-menu {\n"
    "display: none;\n"
  "}\n"
  /* Hide checkbox */
  ".side-menu:checked ~ nav{\n"
    "max-height: 100%;\n"
  "}"
  ".side-menu:checked ~ .hamb .hamb-line {"
    "background: transparent;"
  "}"
  ".side-menu:checked ~ .hamb .hamb-line::before {"
    "transform: rotate(-45deg);"
    "top:0;"
  "}"
  ".side-menu:checked ~ .hamb .hamb-line::after {"
    "transform: rotate(45deg);"
    "top:0;"
  "}"
  /* Responsiveness */
  "@media (min-width: 768px) {"
    ".nav{"
        "max-height: none;"
        "top: 0;"
        "position: relative;"
        "float: right;"
        "width: fit-content;"
        "background-color: transparent;"
    "}"
    ".menu li{"
        "float: left;"
    "}"
    ".menu a:hover{"
        "background-color: transparent;"
        "color: var(--gray);"
    "}"

    ".hamb{"
        "display: none;"
    "}"
  "}"
;